version: '3'

services:
  # ncm-inference:
  #   image: philippzagar/ncm-inference:latest
  #   container_name: "ncm-inference"
  #   build: ./inference
  #   ports:
  #     - "3000:80" # Map host port 3000 to container port 80
  #     - "10123:10123" # Socket connection to ncm-debian (so libmoep)
  #   networks:
  #     - ncm-network
  #   restart: unless-stopped
  #   depends_on:
  #     ncm-server:
  #       condition: service_started
  #   # extra_hosts:
  #   #   - "host.docker.internal:host-gateway"

  ncm-server:
    image: philippzagar/ncm-server:latest
    container_name: "ncm-server"
    build: ./server
    ports:
      - "8080:8080" # Map host port 8080 to container port 80
      - "5000:5000" # Socket connection to ncm-inference
      - "10123:10123" # Socket connection to ncm-debian (so libmoep)
    networks:
      - ncm-network
    restart: unless-stopped

  ncm-debian:
    image: philippzagar/ncm-debian:latest
    container_name: "ncm-debian"
    build: ./ncm_mock
    restart: unless-stopped
    depends_on:
      ncm-server:
        condition: service_started
      # ncm-inference:
      #   condition: service_started
    privileged: true
    cap_add:
      - SYS_PTRACE
    network_mode: host

networks:
  ncm-network:
