version: '3'

services:
  ncm-server:
    image: philippzagar/ncm-server:latest
    container_name: "ncm-server"
    build: ./server
    ports:
      - "8080:8080" # Map host port 8080 to container port 80
      - "5000:5000" # Socket connection to ncm-inference
      - "10123:10123" # Socket connection to ncm-debian (so libmoep)
    networks:
      - ncm-network
    restart: unless-stopped

  ncm-debian:
    image: philippzagar/ncm-debian:latest
    container_name: "ncm-debian"
    build: ./ncm_mock
    restart: unless-stopped
    depends_on:
      ncm-server:
        condition: service_started
    privileged: true
    cap_add:
      - SYS_PTRACE
    network_mode: host

networks:
  ncm-network:
